default: &default
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  adapter: mysql2
  username: root
  password:
  host: localhost
  database: livenote_1109_development

test:
  <<: *default
  adapter: mysql2
  username: root
  password:
  host: localhost
  database: livenote_1109_test

production:
  <<: *default
  adapter: postgresql
  password: <%= ENV['LIVENOTE_1109_DATABASE_PASSWORD'] %>